---
  - name: "Instalar zabbix_agent2"
    hosts: localhost
    connection: local
    tasks:
    - name: Add multiple repositories into the same file (1/2)
      ansible.builtin.yum_repository:
        name: zabbix
        description: zabbix
        baseurl: https://repo.zabbix.com/zabbix/4.4/rhel/8/x86_64/
        gpgcheck: yes
        gpgkey: https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX-A14FE591
        enabled: yes
    - name: Instalando zabbix
      ansible.builtin.yum:
        name: zabbix-agent2
        state: latest
    - name: configurar server agent
      ansible.builtin.lineinfile:
        path: /etc/zabbix/zabbix_agent2.conf
        regexp: '^Server='
        line: Server=127.0.0.1,44.201.81.17
    - name: configurar ServiceActive
      ansible.builtin.lineinfile:
        path: /etc/zabbix/zabbix_agent2.conf
        regexp: '^ServerActive='
        line: ServerActive=127.0.0.1,44.201.81.17
    - name: Habilitar puerto 10050
      ansible.builtin.shell: /etc/ansible/scripts/habilitar_port.sh
    - name: Start service zabbix
      ansible.builtin.service:
        name: zabbix-agent2
        state: started
